export const PLAYER_STASTITICS = [
  {
    name: "Kylian Mbappé",
    team: "França",
    acronym: "FRA",
    goals: 10,
    assists: 4,
  },
  {
    name: "Lionel Messi",
    team: "Argentina",
    acronym: "ARG",
    goals: 8,
    assists: 4,
  },
  {
    name: "Erling Haaland",
    team: "Noruega",
    acronym: "NOR",
    goals: 7,
    assists: 0,
  },
  {
    name: "Jude Bellingham",
    team: "Inglaterra",
    acronym: "ING",
    goals: 7,
    assists: 0,
  },
  {
    name: "Ousmane Dembélé",
    team: "França",
    acronym: "FRA",
    goals: 6,
    assists: 2,
  },
  {
    name: "Harry Kane",
    team: "Inglaterra",
    acronym: "ING",
    goals: 6,
    assists: 1,
  },
  {
    name: "Mikel Oyarzabal",
    team: "Espanha",
    acronym: "ESP",
    goals: 5,
    assists: 1,
  },
  {
    name: "Lautaro Martínez",
    team: "Argentina",
    acronym: "ARG",
    goals: 4,
    assists: 1,
  },
  {
    name: "Julián Álvarez",
    team: "Argentina",
    acronym: "ARG",
    goals: 4,
    assists: 0,
  },
  {
    name: "Ismaila Sarr",
    team: "Senegal",
    acronym: "SEN",
    goals: 3,
    assists: 2,
  },
  {
    name: "Vinicius Jr.",
    team: "Brasil",
    acronym: "BRA",
    goals: 3,
    assists: 2,
  },
  {
    name: "Lamine Yamal",
    team: "Espanha",
    acronym: "ESP",
    goals: 2,
    assists: 2,
  },
  {
    name: "Ferran Torres",
    team: "Espanha",
    acronym: "ESP",
    goals: 2,
    assists: 1,
  },
  {
    name: "Enzo Fernández",
    team: "Argentina",
    acronym: "ARG",
    goals: 2,
    assists: 1,
  },
  {
    name: "Mikel Merino",
    team: "Espanha",
    acronym: "ESP",
    goals: 2,
    assists: 0,
  },
  {
    name: "Pedro Porro",
    team: "Espanha",
    acronym: "ESP",
    goals: 2,
    assists: 0,
  },
  {
    name: "Bruno Guimarães",
    team: "Brasil",
    acronym: "BRA",
    goals: 1,
    assists: 4,
  },
  {
    name: "Brahim Díaz",
    team: "Espanha",
    acronym: "ESP",
    goals: 1,
    assists: 4,
  },
  {
    name: "Martin Ødegaard",
    team: "Noruega",
    acronym: "NOR",
    goals: 1,
    assists: 4,
  },
  {
    name: "Michael Olise",
    team: "França",
    acronym: "FRA",
    goals: 0,
    assists: 7,
  },
];

export const TEAM_STATS = [
  {
    team: "Espanha",
    matchesPlayed: 8,
    wins: 6,
    draws: 1,
    losses: 0,
    goalsScored: 15,
    goalsConceded: 1,
  },
  {
    team: "Argentina",
    matchesPlayed: 8,
    wins: 5,
    draws: 0,
    losses: 2,
    goalsScored: 19,
    goalsConceded: 7,
  },
  {
    team: "França",
    matchesPlayed: 8,
    wins: 6,
    draws: 0,
    losses: 2,
    goalsScored: 22,
    goalsConceded: 6,
  },
  {
    team: "Inglaterra",
    matchesPlayed: 8,
    wins: 5,
    draws: 1,
    losses: 2,
    goalsScored: 15,
    goalsConceded: 9,
  },
  {
    team: "Marrocos",
    matchesPlayed: 6,
    wins: 4,
    draws: 1,
    losses: 1,
    goalsScored: 9,
    goalsConceded: 6,
  },
  {
    team: "Noruega",
    matchesPlayed: 6,
    wins: 4,
    draws: 0,
    losses: 2,
    goalsScored: 12,
    goalsConceded: 5,
  },
  {
    team: "Bélgica",
    matchesPlayed: 5,
    wins: 3,
    draws: 1,
    losses: 1,
    goalsScored: 11,
    goalsConceded: 7,
  },
  {
    team: "Brasil",
    matchesPlayed: 5,
    wins: 3,
    draws: 0,
    losses: 2,
    goalsScored: 8,
    goalsConceded: 4,
  },
  {
    team: "Suíça",
    matchesPlayed: 5,
    wins: 3,
    draws: 1,
    losses: 1,
    goalsScored: 6,
    goalsConceded: 6,
  },
  {
    team: "Colômbia",
    matchesPlayed: 4,
    wins: 2,
    draws: 1,
    losses: 1,
    goalsScored: 5,
    goalsConceded: 3,
  },
  {
    team: "Portugal",
    matchesPlayed: 4,
    wins: 2,
    draws: 0,
    losses: 2,
    goalsScored: 6,
    goalsConceded: 4,
  },
  {
    team: "México",
    matchesPlayed: 4,
    wins: 3,
    draws: 0,
    losses: 1,
    goalsScored: 7,
    goalsConceded: 5,
  },
  {
    team: "Egito",
    matchesPlayed: 4,
    wins: 2,
    draws: 1,
    losses: 1,
    goalsScored: 5,
    goalsConceded: 5,
  },
  {
    team: "Alemanha",
    matchesPlayed: 4,
    wins: 2,
    draws: 0,
    losses: 2,
    goalsScored: 8,
    goalsConceded: 5,
  },
  {
    team: "Holanda",
    matchesPlayed: 4,
    wins: 2,
    draws: 1,
    losses: 1,
    goalsScored: 5,
    goalsConceded: 4,
  },
  {
    team: "Estados Unidos",
    matchesPlayed: 4,
    wins: 2,
    draws: 0,
    losses: 2,
    goalsScored: 5,
    goalsConceded: 5,
  },
  {
    team: "Senegal",
    matchesPlayed: 4,
    wins: 2,
    draws: 0,
    losses: 2,
    goalsScored: 7,
    goalsConceded: 6,
  },
  {
    team: "Paraguai",
    matchesPlayed: 4,
    wins: 2,
    draws: 1,
    losses: 1,
    goalsScored: 3,
    goalsConceded: 2,
  },
  {
    team: "Canadá",
    matchesPlayed: 4,
    wins: 1,
    draws: 0,
    losses: 3,
    goalsScored: 3,
    goalsConceded: 6,
  },
  {
    team: "Croácia",
    matchesPlayed: 4,
    wins: 1,
    draws: 0,
    losses: 3,
    goalsScored: 4,
    goalsConceded: 6,
  },
  {
    team: "Gana",
    matchesPlayed: 3,
    wins: 1,
    draws: 0,
    losses: 2,
    goalsScored: 2,
    goalsConceded: 4,
  },
  {
    team: "África do Sul",
    matchesPlayed: 3,
    wins: 0,
    draws: 1,
    losses: 2,
    goalsScored: 1,
    goalsConceded: 4,
  },
  {
    team: "Japão",
    matchesPlayed: 3,
    wins: 1,
    draws: 0,
    losses: 2,
    goalsScored: 3,
    goalsConceded: 4,
  },
  {
    team: "Congo",
    matchesPlayed: 3,
    wins: 1,
    draws: 0,
    losses: 2,
    goalsScored: 3,
    goalsConceded: 4,
  },
  {
    team: "Bósnia e Herz.",
    matchesPlayed: 3,
    wins: 0,
    draws: 0,
    losses: 3,
    goalsScored: 1,
    goalsConceded: 6,
  },
  {
    team: "Argélia",
    matchesPlayed: 3,
    wins: 0,
    draws: 0,
    losses: 3,
    goalsScored: 1,
    goalsConceded: 5,
  },
  {
    team: "Áustria",
    matchesPlayed: 3,
    wins: 0,
    draws: 0,
    losses: 3,
    goalsScored: 1,
    goalsConceded: 6,
  },
  {
    team: "Austrália",
    matchesPlayed: 3,
    wins: 0,
    draws: 1,
    losses: 2,
    goalsScored: 2,
    goalsConceded: 4,
  },
  {
    team: "Jordânia",
    matchesPlayed: 3,
    wins: 0,
    draws: 0,
    losses: 3,
    goalsScored: 0,
    goalsConceded: 6,
  },
  {
    team: "Cabo Verde",
    matchesPlayed: 4,
    wins: 1,
    draws: 0,
    losses: 3,
    goalsScored: 3,
    goalsConceded: 7,
  },
  {
    team: "Suécia",
    matchesPlayed: 3,
    wins: 1,
    draws: 0,
    losses: 2,
    goalsScored: 5,
    goalsConceded: 6,
  },
];

export const CURIOSITIES = [
  "A Copa 2026 foi a primeira com 48 seleções e 104 jogos, o maior torneio da história.",
  "308 gols foram marcados no total — recorde absoluto em uma Copa do Mundo.",
  "O jogo França 4x6 Inglaterra pelo terceiro lugar foi o com mais gols na história das disputas de terceiro lugar.",
  "Mbappé terminou a Copa como artilheiro histórico de todas as Copas com 22 gols no total, superando Messi.",
  "Mbappé venceu a Bota de Ouro com 10 gols, dois a mais que Messi (8).",
  "Michael Olise foi o líder em assistências do torneio com 7.",
  "Espanha terminou com 6 clean sheets — o melhor aproveitamento defensivo do torneio.",
  "Argentina marcou 19 gols em 8 jogos — mais do que qualquer outra seleção.",
  "França concedeu apenas 1 gol nos primeiros 7 jogos antes da goleada para a Inglaterra.",
  "Noruega eliminou o Brasil nas oitavas com Haaland marcando duas vezes.",
  "Marrocos eliminou a Holanda nas oitavas e chegou às quartas de final.",
  "Cabo Verde fez história chegando às oitavas de final pela primeira vez.",
  "Paraguai eliminou a Alemanha nas oitavas nos pênaltis (4-3).",
  "Curaçao marcou seu primeiro gol na história das Copas do Mundo.",
  "África do Sul fez sua melhor campanha histórica chegando às oitavas de final.",
  "A final foi Espanha x Argentina — as duas melhores seleções do ranking FIFA.",
  "Ferran Torres marcou o único gol da final na prorrogação para dar o título à Espanha.",
  "Espanha venceu sua quarta Copa do Mundo, igualando a Itália.",
  "Messi disputou sua última Copa do Mundo e chegou até a final com 8 gols.",
  "Rodri venceu a Bola de Ouro, Unai Simón a Luva de Ouro e Pau Cubarsí o Melhor Jovem.",
  "A Copa foi sediada em três países pela primeira vez: EUA, México e Canadá.",
  "Inglaterra terminou em terceiro — seu melhor resultado desde o título em 1966.",
  "Bellingham marcou 7 gols e foi o maior artilheiro inglês em uma única edição de Copa.",
  "Bukayo Saka fez hat-trick no jogo do terceiro lugar contra a França.",
  "Declan Rice marcou o gol mais rápido do torneio — no 3º minuto contra a França.",
];

export const STASTITICS_STAGES = {
  PLAYER: {
    label: "Jogadores",
    id: "1",
  },
  TEAMS: {
    label: "Times",
    id: "2",
  },
  CURIOSITIES: {
    label: "Curiosidades",
    id: "3",
  },
};

export const STASTITICS_STAGES_ARRAY = [
  STASTITICS_STAGES.PLAYER,
  STASTITICS_STAGES.TEAMS,
  STASTITICS_STAGES.CURIOSITIES,
];
