export const PLAYER_STASTITICS = [
  {
    name: "Kylian Mbappé",
    team: "França",
    acronym: "FRA",
    goals: 8,
    assists: 3,
  },
  {
    name: "Lionel Messi",
    acronym: "ARG",
    team: "Argentina",
    goals: 8,
    assists: 2,
  },
  {
    name: "Erling Haaland",
    team: "Noruega",
    acronym: "NOR",
    goals: 7,
    assists: 0,
  },
  {
    name: "Harry Kane",
    team: "Inglaterra",
    acronym: "ING",
    goals: 6,
    assists: 1,
  },
  {
    name: "Jude Bellingham",
    team: "Inglaterra",
    acronym: "ING",
    goals: 6,
    assists: 1,
  },
  {
    name: "Ousmane Dembélé",
    team: "França",
    acronym: "FRA",
    goals: 5,
    assists: 2,
  },
  {
    name: "Mikel Oyarzabal",
    team: "Espanha",
    acronym: "ESP",
    goals: 5,
    assists: 1,
  },
  {
    name: "Lautaro Martínez",
    team: "Argentina",
    acronym: "ARG",
    goals: 4,
    assists: 1,
  },
  {
    name: "Julián Álvarez",
    team: "Argentina",
    acronym: "ARG",
    goals: 4,
    assists: 0,
  },
  {
    name: "Vinicius Jr.",
    team: "Brasil",
    acronym: "BRA",
    goals: 3,
    assists: 2,
  },
];

export const TEAM_STATS = [
  {
    teamId: 37,
    team: "Argentina",
    acronym: "ARG",
    matchesPlayed: 6,
    wins: 5,
    draws: 0,
    losses: 1,
    goalsScored: 19,
    goalsConceded: 6,
    cleanSheets: 1,
  },
  {
    teamId: 33,
    team: "França",
    acronym: "FRA",
    matchesPlayed: 7,
    wins: 6,
    draws: 0,
    losses: 1,
    goalsScored: 16,
    goalsConceded: 1,
    cleanSheets: 5,
  },
  {
    teamId: 29,
    team: "Espanha",
    acronym: "ESP",
    matchesPlayed: 7,
    wins: 5,
    draws: 1,
    losses: 0,
    goalsScored: 14,
    goalsConceded: 1,
    cleanSheets: 6,
  },
  {
    teamId: 45,
    team: "Inglaterra",
    acronym: "ING",
    matchesPlayed: 7,
    wins: 5,
    draws: 1,
    losses: 1,
    goalsScored: 12,
    goalsConceded: 6,
    cleanSheets: 2,
  },
  {
    teamId: 10,
    team: "Marrocos",
    acronym: "MAR",
    matchesPlayed: 6,
    wins: 4,
    draws: 1,
    losses: 1,
    goalsScored: 9,
    goalsConceded: 6,
    cleanSheets: 2,
  },
  {
    teamId: 35,
    team: "Noruega",
    acronym: "NOR",
    matchesPlayed: 6,
    wins: 4,
    draws: 0,
    losses: 2,
    goalsScored: 12,
    goalsConceded: 5,
    cleanSheets: 1,
  },
  {
    teamId: 25,
    team: "Bélgica",
    acronym: "BEL",
    matchesPlayed: 5,
    wins: 3,
    draws: 1,
    losses: 1,
    goalsScored: 11,
    goalsConceded: 7,
    cleanSheets: 1,
  },
  {
    teamId: 9,
    team: "Brasil",
    acronym: "BRA",
    matchesPlayed: 5,
    wins: 3,
    draws: 0,
    losses: 2,
    goalsScored: 8,
    goalsConceded: 4,
    cleanSheets: 1,
  },
];

export const CURIOSITIES = [
  { text: "Mbappé e Messi dividem a artilharia com 8 gols cada" },
  { text: "Espanha é a equipe com mais clean sheets do torneio (6)" },
  { text: "Argentina marcou 19 gols — mais do que qualquer outro time" },
  { text: "França concedeu apenas 1 gol em 7 jogos" },
  { text: "Haaland eliminou o Brasil com um doblete nas oitavas" },
  { text: "Argentina venceu 3 jogos seguidos após estar perdendo" },
  { text: "Bellingham marcou 6 gols e foi o herói da Inglaterra" },
  { text: "Espanha e Argentina se encontram na final — top 2 do ranking FIFA" },
];

export const STASTITICS_STAGES = {
  PLAYER: {
    label: "Jogadores",
    id: "1",
  },
  TEAMS: {
    label: "Times",
    id: "2",
  },
  CURIOSITIES: {
    label: "Curiosidades",
    id: "3",
  },
};

export const STASTITICS_STAGES_ARRAY = [
  STASTITICS_STAGES.PLAYER,
  STASTITICS_STAGES.TEAMS,
  STASTITICS_STAGES.CURIOSITIES,
];
