export const TOP_SCORES = [
  { name: "Kylian Mbappé", team: "FRA", teamId: 33, goals: 8, assists: 3 },
  { name: "Lionel Messi", team: "ARG", teamId: 37, goals: 8, assists: 2 },
  { name: "Erling Haaland", team: "NOR", teamId: 35, goals: 7, assists: 0 },
  { name: "Harry Kane", team: "ING", teamId: 45, goals: 6, assists: 1 },
  { name: "Jude Bellingham", team: "ING", teamId: 45, goals: 6, assists: 1 },
  { name: "Ousmane Dembélé", team: "FRA", teamId: 33, goals: 5, assists: 2 },
  { name: "Mikel Oyarzabal", team: "ESP", teamId: 29, goals: 5, assists: 1 },
  { name: "Lautaro Martínez", team: "ARG", teamId: 37, goals: 4, assists: 1 },
  { name: "Julián Álvarez", team: "ARG", teamId: 37, goals: 4, assists: 0 },
  { name: "Vinicius Jr.", team: "BRA", teamId: 9, goals: 3, assists: 2 },
];

export const TOP_ASSISTS = [
  { name: "Michael Olise", team: "FRA", teamId: 33, assists: 5 },
  { name: "Bruno Guimarães", team: "BRA", teamId: 9, assists: 4 },
  { name: "Martin Ødegaard", team: "NOR", teamId: 35, assists: 4 },
  { name: "Brahim Díaz", team: "ESP", teamId: 29, assists: 4 },
  { name: "Lionel Messi", team: "ARG", teamId: 37, assists: 2 },
  { name: "Lamine Yamal", team: "ESP", teamId: 29, assists: 2 },
  { name: "Kylian Mbappé", team: "FRA", teamId: 33, assists: 3 },
];

export const TEAM_STATS = [
  {
    teamId: 37,
    team: "Argentina",
    acronym: "ARG",
    matchesPlayed: 6,
    wins: 5,
    draws: 0,
    losses: 1,
    goalsScored: 19,
    goalsConceded: 6,
    cleanSheets: 1,
  },
  {
    teamId: 33,
    team: "França",
    acronym: "FRA",
    matchesPlayed: 7,
    wins: 6,
    draws: 0,
    losses: 1,
    goalsScored: 16,
    goalsConceded: 1,
    cleanSheets: 5,
  },
  {
    teamId: 29,
    team: "Espanha",
    acronym: "ESP",
    matchesPlayed: 7,
    wins: 5,
    draws: 1,
    losses: 0,
    goalsScored: 14,
    goalsConceded: 1,
    cleanSheets: 6,
  },
  {
    teamId: 45,
    team: "Inglaterra",
    acronym: "ING",
    matchesPlayed: 7,
    wins: 5,
    draws: 1,
    losses: 1,
    goalsScored: 12,
    goalsConceded: 6,
    cleanSheets: 2,
  },
  {
    teamId: 10,
    team: "Marrocos",
    acronym: "MAR",
    matchesPlayed: 6,
    wins: 4,
    draws: 1,
    losses: 1,
    goalsScored: 9,
    goalsConceded: 6,
    cleanSheets: 2,
  },
  {
    teamId: 35,
    team: "Noruega",
    acronym: "NOR",
    matchesPlayed: 6,
    wins: 4,
    draws: 0,
    losses: 2,
    goalsScored: 12,
    goalsConceded: 5,
    cleanSheets: 1,
  },
  {
    teamId: 25,
    team: "Bélgica",
    acronym: "BEL",
    matchesPlayed: 5,
    wins: 3,
    draws: 1,
    losses: 1,
    goalsScored: 11,
    goalsConceded: 7,
    cleanSheets: 1,
  },
  {
    teamId: 9,
    team: "Brasil",
    acronym: "BRA",
    matchesPlayed: 5,
    wins: 3,
    draws: 0,
    losses: 2,
    goalsScored: 8,
    goalsConceded: 4,
    cleanSheets: 1,
  },
];

export const CURIOSITIES = [
  { text: "Mbappé e Messi dividem a artilharia com 8 gols cada" },
  { text: "Espanha é a equipe com mais clean sheets do torneio (6)" },
  { text: "Argentina marcou 19 gols — mais do que qualquer outro time" },
  { text: "França concedeu apenas 1 gol em 7 jogos" },
  { text: "Haaland eliminou o Brasil com um doblete nas oitavas" },
  { text: "Argentina venceu 3 jogos seguidos após estar perdendo" },
  { text: "Bellingham marcou 6 gols e foi o herói da Inglaterra" },
  { text: "Espanha e Argentina se encontram na final — top 2 do ranking FIFA" },
];
