export const EIGHT_FINALS_UPDATE = [
  {
    id: "r16_1",
    homeTeam: 5,
    awayTeam: 10,
    homeScore: 0,
    awayScore: 3,
    penaltyWinner: null,
    finished: true,
  },
  {
    id: "r16_2",
    homeTeam: 15,
    awayTeam: 33,
    homeScore: 0,
    awayScore: 1,
    penaltyWinner: null,
    finished: true,
  },
  {
    id: "r16_3",
    homeTeam: 9,
    awayTeam: 35,
    homeScore: null,
    awayScore: null,
    penaltyWinner: null,
    finished: false,
  },
  {
    id: "r16_4",
    homeTeam: 1,
    awayTeam: 45,
    homeScore: null,
    awayScore: null,
    penaltyWinner: null,
    finished: false,
  },
  {
    id: "r16_5",
    homeTeam: 41,
    awayTeam: 29,
    homeScore: null,
    awayScore: null,
    penaltyWinner: null,
    finished: false,
  },
  {
    id: "r16_6",
    homeTeam: 13,
    awayTeam: 25,
    homeScore: null,
    awayScore: null,
    penaltyWinner: null,
    finished: false,
  },
  {
    id: "r16_7",
    homeTeam: 37,
    awayTeam: 27,
    homeScore: null,
    awayScore: null,
    penaltyWinner: null,
    finished: false,
  },
  {
    id: "r16_8",
    homeTeam: 6,
    awayTeam: 42,
    homeScore: null,
    awayScore: null,
    penaltyWinner: null,
    finished: false,
  },
];
