export const TEAMS = [
  { id: 1, name: "México", acronym: "MEX", group: "A" },
  { id: 2, name: "Coreia do Sul", acronym: "COR", group: "A" },
  { id: 3, name: "África do Sul", acronym: "AFS", group: "A" },
  { id: 4, name: "Tchéquia", acronym: "TCH", group: "A" },
  { id: 5, name: "Canadá", acronym: "CAN", group: "B" },
  { id: 6, name: "Suíça", acronym: "SUI", group: "B" },
  { id: 7, name: "Catar", acronym: "CAT", group: "B" },
  { id: 8, name: "Bósnia e Herzegovina", acronym: "BIH", group: "B" },
  { id: 9, name: "Brasil", acronym: "BRA", group: "C" },
  { id: 10, name: "Marrocos", acronym: "MAR", group: "C" },
  { id: 11, name: "Escócia", acronym: "ESC", group: "C" },
  { id: 12, name: "Haiti", acronym: "HAI", group: "C" },
  { id: 13, name: "Estados Unidos", acronym: "EUA", group: "D" },
  { id: 14, name: "Austrália", acronym: "AUS", group: "D" },
  { id: 15, name: "Paraguai", acronym: "PAR", group: "D" },
  { id: 16, name: "Turquia", acronym: "TUR", group: "D" },
  { id: 17, name: "Alemanha", acronym: "ALE", group: "E" },
  { id: 18, name: "Equador", acronym: "EQU", group: "E" },
  { id: 19, name: "Costa do Marfim", acronym: "CIV", group: "E" },
  { id: 20, name: "Curaçao", acronym: "CUW", group: "E" },
  { id: 21, name: "Holanda", acronym: "HOL", group: "F" },
  { id: 22, name: "Japão", acronym: "JAP", group: "F" },
  { id: 23, name: "Tunísia", acronym: "TUN", group: "F" },
  { id: 24, name: "Suécia", acronym: "SUE", group: "F" },
  { id: 25, name: "Bélgica", acronym: "BEL", group: "G" },
  { id: 26, name: "Irã", acronym: "IRA", group: "G" },
  { id: 27, name: "Egito", acronym: "EGI", group: "G" },
  { id: 28, name: "Nova Zelândia", acronym: "NZL", group: "G" },
  { id: 29, name: "Espanha", acronym: "ESP", group: "H" },
  { id: 30, name: "Uruguai", acronym: "URU", group: "H" },
  { id: 31, name: "Arábia Saudita", acronym: "ARS", group: "H" },
  { id: 32, name: "Cabo Verde", acronym: "CAV", group: "H" },
  { id: 33, name: "França", acronym: "FRA", group: "I" },
  { id: 34, name: "Senegal", acronym: "SEN", group: "I" },
  { id: 35, name: "Noruega", acronym: "NOR", group: "I" },
  { id: 36, name: "Iraque", acronym: "IRQ", group: "I" },
  { id: 37, name: "Argentina", acronym: "ARG", group: "J" },
  { id: 38, name: "Áustria", acronym: "AUT", group: "J" },
  { id: 39, name: "Argélia", acronym: "ALG", group: "J" },
  { id: 40, name: "Jordânia", acronym: "JOR", group: "J" },
  { id: 41, name: "Portugal", acronym: "POR", group: "K" },
  { id: 42, name: "Colômbia", acronym: "COL", group: "K" },
  { id: 43, name: "Uzbequistão", acronym: "UZB", group: "K" },
  { id: 44, name: "Congo", acronym: "COD", group: "K" },
  { id: 45, name: "Inglaterra", acronym: "ING", group: "L" },
  { id: 46, name: "Croácia", acronym: "CRO", group: "L" },
  { id: 47, name: "Panamá", acronym: "PAN", group: "L" },
  { id: 48, name: "Gana", acronym: "GAN", group: "L" },
];
